# Generated by Django 4.2.7 on 2023-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_meal_time_attendance_dinner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Dinner',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='breakfast',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lunch',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
