# Generated by Django 4.2.7 on 2023-11-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_menu_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='date',
            new_name='dat1e',
        ),
    ]
