# Generated by Django 4.2.7 on 2023-11-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_rename_date_menu_dat1e'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='dat1e',
            new_name='date',
        ),
    ]
