# Generated by Django 4.2.7 on 2023-11-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='person',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
