# Generated by Django 4.2.7 on 2023-11-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_rating_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='avg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
