# Generated by Django 4.2.7 on 2023-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_alter_rating_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='at2',
            name='date',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='rating',
            name='avg',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='person',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
    ]
