# Generated by Django 4.2.7 on 2023-11-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_image23_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image23',
            name='image',
        ),
    ]
