# Generated by Django 4.2.7 on 2023-11-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_image23_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='meal_time',
            new_name='Dinner',
        ),
        migrations.AddField(
            model_name='attendance',
            name='breakfast',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='lunch',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
