# Generated by Django 4.2.7 on 2023-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_attendance_dinner_alter_attendance_breakfast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AT2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('Dinner', models.CharField(default='0', max_length=20)),
                ('breakfast', models.CharField(default='0', max_length=20)),
                ('lunch', models.CharField(default='0', max_length=20)),
            ],
        ),
    ]
