# Generated by Django 4.2.7 on 2023-11-29 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_menu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image23',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image23',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.menuitem'),
        ),
    ]
