# Generated by Django 4.2.7 on 2023-11-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_excelfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
        ),
    ]
