# Generated by Django 4.2.7 on 2023-12-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_alter_items_item1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item1',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item10',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item11',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item12',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item13',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item14',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item15',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item16',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item17',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item18',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item19',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item2',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item20',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item21',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item22',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item23',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item24',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item3',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item4',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item5',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item6',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item7',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item8',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='item9',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='.', max_length=111),
        ),
    ]
