# Generated by Django 4.2.7 on 2023-11-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_alter_items_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='menu_item',
            field=models.CharField(max_length=90),
        ),
    ]
